apiVersion: v1
kind: Service
metadata:
  name: antelope
  namespace: antelope
spec:
  selector:
    app.kubernetes.io/name: antelope
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
