name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      id: extract_branch
    - uses: actions/checkout@v1
    - name: Check and build
      uses: cedrickring/golang-action@1.3.0
    - uses: vrutkovs/action-s2i@master
      with:
        path: ./cmd/service
        base: registry.fedoraproject.org/f29/golang
        image: antelope:src
    - uses: vrutkovs/action-bin-container@master
      with:
        source_image: antelope:src
        source_path: /opt/app-root/gobinary
        binary_base: registry.access.redhat.com/ubi8/ubi-minimal:latest
        binary_path: /usr/local/bin/antelope
        binary_image: quay.io/vrutkovs/antelope:${{ steps.extract_branch.outputs.branch }}
      if: github.event_name == 'push'
    - name: push the image
      uses: jerray/publish-docker-action@master
      with:
        username: vrutkovs
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: quay.io
        repository: quay.io/vrutkovs/antelope
      if: github.event_name == 'push'
